### ISSUE TITLE
Include LuCi for EA3500 OpenWRT SSA autobuilder

### ISSUE THREAD

**Issue by MayorBug** [cilynx/Candyhouse-Linux#2]
Exactly what the title says would be a nice addition.

**Comment by cilynx** [comment]
Please test this SSA and let me know if it works for you.  It should have LuCI and wpad-mini available out-of-the-box.  You will need to start with an Ethernet connection, but you should be able to enable WiFi just by clicking Enable in the LuCI interface.

http://www.wolfteck.com/projects/candyhouse/openwrt/openwrt-kirkwood-ea3500-pri.ssa
http://www.wolfteck.com/projects/candyhouse/openwrt/openwrt-kirkwood-ea3500-alt.ssa

**Comment by MayorBug** [comment]
Those builds will not boot on my EA3500. The power led will blink for about 10 secs and then will turn off.

**Comment by cilynx** [comment]
Just posted a couple new ones.  One of my patched OpenWRT patches (horray meta build system) wasn't applying correctly so the partition table was screwed up.  I think I've gotten it straightened out now.  Can you check these out?

http://www.wolfteck.com/projects/candyhouse/openwrt/openwrt-kirkwood-ea3500-pri.ssa
http://www.wolfteck.com/projects/candyhouse/openwrt/openwrt-kirkwood-ea3500-alt.ssa

**Comment by MayorBug** [comment]
Those work now. Even opkg.conf is now working by default. 
Thanks!
